# Treehouse Configuration
# This file consolidates service configuration, environment variables, and health checks

core_services:
  ui:
    command: "pnpm vite dev --open"
    health_check:
      url: "http://localhost:3000"
      codes: [200, 302]
      interval_seconds: 5
      timeout_seconds: 5

  temporal:
    command: "temporal server start-dev"
    health_check:
      url: "http://localhost:8081/healthz"
      codes: [200, 302]
      interval_seconds: 5
      timeout_seconds: 5

  ui-server:
    command: "cd server && go run ./cmd/server/main.go --env development start"
    health_check:
      url: "http://localhost:8233/health"
      codes: [200, 302]
      interval_seconds: 5
      timeout_seconds: 5

# Optional services can be added here as needed
optional_services: {}

# Global environment variables
global_env:
  ENVIRONMENT: "development" 